### PR TITLE
Sdk 8.1.0

### PR DESCRIPTION
**Pull request by souheib93**

### CODE REVIEW

**Comment by suzukieng** [comment]
Build fails, with Gradle sync issues due to a transitive dependency on a PDF viewer library?

```
Executing tasks: [:app:clean, :app:assembleDebug] in project /Users/ahs/pixelverse/hin/vid-android/HINVideoIdent


> Configure project :app
AGPBI: {"kind":"warning","text":"The option setting 'android.defaults.buildfeatures.buildconfig=true' is deprecated.\nThe current default is 'false'.\nIt will be removed in version 9.0 of the Android Gradle plugin.\nYou can resolve this warning in Android Studio via `Refactor` > `Migrate BuildConfig to Gradle Build Files`","sources":[{}]}

> Task :app:clean UP-TO-DATE
> Task :app:createDebugVariantModel
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:javaPreCompileDebug
> Task :app:checkDebugAarMetadata FAILED
> Task :app:generateDebugResValues
> Task :app:mapDebugSourceSetPaths FAILED
> Task :app:generateDebugResources
> Task :app:mergeDebugResources FAILED
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :app:processDebugMainManifest FAILED
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets FAILED
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:mergeDebugJavaResource FAILED
> Task :app:checkDebugDuplicateClasses FAILED
> Task :app:desugarDebugFileDependencies FAILED
> Task :app:mergeDebugJniLibFolders
> Task :app:mergeDebugNativeLibs FAILED
> Task :app:validateSigningDebug
> Task :app:writeDebugAppMetadata
> Task :app:writeDebugSigningConfigVersions

FAILURE: Build completed with 9 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.barteksc:android-pdf-viewer:2.6.0.
     Required by:
         project :app > de.idnow.sdk:idnow-android-sdk:8.1.0
      > Could not resolve com.github.barteksc:android-pdf-viewer:2.6.0.
         > Could not get resource 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/2.6.0/android-pdf-viewer-2.6.0.pom'.
            > Could not GET 'https://jitpack.io/com/github/barteksc/android-pdf-viewer/2.6.0/android-pdf-viewer-2.6.0.pom'. Received status code 401 from server: Unauthorized
```

**Comment by souheib93** [comment]
please add `maven { url 'https://jitpack.io' } ` to the repositories in build.gradle file

**Comment by suzukieng** [comment]
@souheib93 i've already done that – excerpt from `settings.gradle`:

Screenshot 2024-06-12 at 15 15 25

It does GET to jitpack.io, but receives HTTP 401: authorized

**Comment by souheib93** [comment]
I couldn't reproduce it ! we have a sample App https://github.com/idnow/de.idnow.android-sample/tree/sample_without_eid
you can try to clone it, branch `sample_without_eid`

**Comment by suzukieng** [comment]
@souheib93 thank you, that helped. The issue was the jitpack.io Maven repository, removing it helped. After clearing Gradle cache and building with just the following repositories, the build proceeds ok:

```
    repositories {
        google()
        jcenter()
        maven {
            url "https://raw.githubusercontent.com/idnow/de.idnow.android/master"
        }
    }
```

I advise you to update the documentation at https://github.com/idnow/de.idnow.android?tab=readme-ov-file#how-to-import-the-sdk .

**Comment by olgabednarczyk** [comment]
Hi, I also have the `Could not resolve com.github.barteksc:android-pdf-viewer:2.6.0.` issue and suggestions mentioned above didn't work. Also, I cloned the sample repo and got `Could not find com.jaredsburrows:gradle-license-plugin:0.8.41.` error. Am I missing something?

**Comment by souheib93** [comment]
for the above issue could you try :
```
implementation ('de.idnow.sdk:idnow-android-sdk:8.4.0')
    {
        exclude group:"com.github.barteksc", module: "android-pdf-viewer"
    }
    implementation 'com.github.DImuthuUpe:AndroidPdfViewer:2.8.1'
```

**Pull request merged**
